# Generated by Django 4.1.3 on 2022-11-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_enrichments_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrichments',
            new_name='Enrichment',
        ),
    ]
