# Generated by Django 4.1.3 on 2022-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_enrichments_enrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='enrichments',
            field=models.ManyToManyField(to='main_app.enrichment'),
        ),
    ]
